yowainwright/common-utilities

.eslintrc
.gitignore
.markdownlintrc
.prettierrc
README.md
package.json
packages/repeat/package.json
packages/repeat/src/index.ts

- Fixes `.md` table issues
- Adds `repeat` function
----

Documentation updates

---

README.md

fix(root): updates root README.md

---

package.json
packages/compose/README.md
packages/compose/package.json
packages/compose/src/index.test.ts
packages/compose/src/index.ts
yarn.lock

- Updates compose documentation. 
----

feat(compose): adds tests and better docs

---

.github/workflows/nodejs.yml
README.md
package.json
packages/compose/package.json
packages/compose/src/index.ts
packages/head/package.json
packages/head/src/index.ts
packages/pipe/src/index.ts
packages/trace/README.md
packages/trace/src/index.ts
tsconfig.json
yarn.lock

- Adds [tslib](https://www.npmjs.com/package/tslib)
- Adds tests for `trace` finally. 
- Readme  tweaks
----

fix(root): basic updates

---

.eslintignore
README.md
package-lock.json
packages/trace/package.json
packages/trace/src/index.test.ts
yarn.lock

fix(trace): adds tests

---

README.md
packages/compose/README.md
packages/compose/package.json
packages/head/README.md
packages/head/package.json
packages/pipe/README.md
packages/pipe/package.json
packages/repeat/README.md
packages/repeat/package.json
packages/repeat/tsconfig.json
packages/trace/README.md
packages/trace/package.json

fix(root): adds badges

---

packages/fllter-array/package.json
packages/is-object/package.json
packages/merge-objects/package.json

- Fixes privacy issues (make packages public)
----

fix(root): package.json updates

---

README.md
package.json
packages/string-interpolation/README.md
packages/string-interpolation/package.json
packages/string-interpolation/src/index.test.ts
packages/string-interpolation/src/index.ts

- Adds string interpolation package
----

feat(string-interpolation): adds initial package

---

README.md
packages/string-interpolation/package.json
packages/string-interpolation/src/index.js
packages/string-interpolation/tsconfig.json

- Adds interpolation-string files
- Fixes links in the readme
----

fix(root): README update

---

README.md
packages/compose/README.md
packages/fllter-array/README.md
packages/head/README.md
packages/is-object/README.md
packages/merge-objects/README.md
packages/pipe/README.md
packages/repeat/README.md
packages/string-interpolation/README.md
packages/trace/README.md

- Changes `javascript` to `typescript` in `README`s.
----

fix(root): change reference text from ```js to ```ts

---

README.md
packages/compose/README.md
packages/compose/package.json
packages/fllter-array/README.md
packages/fllter-array/package.json
packages/head/README.md
packages/head/package.json
packages/is-object/README.md
packages/is-object/package.json
packages/merge-objects/README.md
packages/merge-objects/package.json
packages/pipe/README.md
packages/pipe/package.json
packages/repeat/README.md
packages/repeat/package.json
packages/string-interpolation/README.md
packages/string-interpolation/package.json
packages/trace/README.md
packages/trace/package.json

- Updates footer & readme notes
----

Remove js in readme

---

README.md

- Fixes merge conflicts in readme. I did something silly. 
----

fix(root): fixes merge conflict in README 😥

---

.eslintrc
.prettierrc
package.json
packages/repeat/src/index.test.ts
yarn.lock

- Switches to the `@heartly/eslint-config-typescript` 
- Uses the `prettier` config that goes along with it. 
----

fix(root): updates eslint/prettier config 😍

---

README.md
package.json
packages/kebab-to-camel-string/README.md
packages/kebab-to-camel-string/package.json
packages/kebab-to-camel-string/src/index.test.ts
packages/kebab-to-camel-string/src/index.ts
packages/kebab-to-camel-string/tsconfig.json

- Adds kebab-to-camel-string package 🍢🐫
----

feat(kebab-to-camel-string): init kebab-to-camel-string package

---

package.json
packages/head/package.json
packages/kebab-to-camel-string/package.json
packages/pipe/package.json
packages/repeat/package.json
packages/string-interpolation/package.json
packages/trace/package.json

- Adds necessary files to `package.json`'s.
----

fix(root): adds module and types to necessary packages's package.json

---

README.md
package.json
packages/compose/src/index.ts
packages/trace/README.md
packages/trim-whitespace/README.md
packages/trim-whitespace/package.json
packages/trim-whitespace/src/index.test.ts
packages/trim-whitespace/src/index.ts
packages/trim-whitespace/tsconfig.json
tsconfig.json
yarn.lock

- Adds **trim-whitespace** common utility. 
----

feat(trim-whitespace): init trim-whitespace

---

README.md

- Fixes README link issue.
----

fix(root): fixes README

---

package.json
packages/compose/README.md
packages/compose/package.json

- Adds a minor update to the compose function
- Removes a few unneeded deps
----

fix(compose): readme tweak; remove unneeded deps

---

README.md
package.json
packages/compose/README.md
packages/compose/package.json
packages/fllter-array/README.md
packages/fllter-array/package.json
packages/head/README.md
packages/head/package.json
packages/is-object/README.md
packages/is-object/package.json
packages/kebab-to-camel-string/README.md
packages/kebab-to-camel-string/package.json
packages/merge-objects/README.md
packages/merge-objects/package.json
packages/pipe/README.md
packages/pipe/package.json
packages/repeat/README.md
packages/repeat/package.json
packages/string-interpolation/README.md
packages/string-interpolation/package.json
packages/trace/README.md
packages/trace/package.json
packages/trim-whitespace/README.md
packages/trim-whitespace/package.json
packages/wait-until-defined/README.md
packages/wait-until-defined/package.json
packages/wait-until-defined/src/index.ts
packages/wait-until-defined/tsconfig.json
yarn.lock

- Fixes packages
- initial work for wait-until-defined
----

Wait until defined

---

package.json
packages/compose/src/index.ts
packages/pipe/src/index.ts
packages/repeat/src/index.ts
packages/wait-until-defined/package.json
packages/wait-until-defined/src/index.test.ts
packages/wait-until-defined/src/index.ts
yarn.lock

- Adds tests to "wait-until-defined"
----

Wait until defined tests

---

README.md
packages/wait-until-defined/README.md
packages/wait-until-defined/package.json

This PR adds the `wait-until-defined` package to the readme. 
- It adds a brief description of the usefulness of each utility.
- It adds a description of why common-utilities might be a good choice for use.  
----

Add wait until defined to root readme

---

README.md
package.json
packages/compose/README.md
packages/compose/package.json
packages/fllter-array/README.md
packages/fllter-array/package.json
packages/head/README.md
packages/head/package.json
packages/is-object/README.md
packages/is-object/package.json
packages/kebab-to-camel-string/README.md
packages/kebab-to-camel-string/package.json
packages/merge-objects/README.md
packages/merge-objects/package.json
packages/merge-objects/src/index.ts
packages/pipe/README.md
packages/pipe/package.json
packages/repeat/README.md
packages/repeat/package.json
packages/string-interpolation/README.md
packages/string-interpolation/package.json
packages/trace/README.md
packages/trace/package.json
packages/trim-whitespace/README.md
packages/trim-whitespace/package.json
packages/wait-until-defined/README.md
packages/wait-until-defined/package.json
yarn.lock

- Removes `function` headers and content
- Adds keywords to `package.json`
----

fix(root): adds keywords, removes function

---

README.md
packages/fllter-array/package.json
packages/head/package.json
packages/is-object/package.json
packages/kebab-to-camel-string/package.json
packages/merge-objects/package.json
packages/pipe/package.json
packages/repeat/package.json
packages/string-interpolation/package.json
packages/trace/package.json
packages/trim-whitespace/package.json
packages/wait-until-defined/package.json

- Feature version bump all packages. 
----

feat(root): feat version bump all pkgs

---

README.md

feat(root): updates readme

---

package.json
packages/compose/package.json
packages/fllter-array/package.json
packages/head/package.json
packages/is-object/package.json
packages/kebab-to-camel-string/package.json
packages/merge-objects/package.json
packages/pipe/package.json
packages/repeat/package.json
packages/string-interpolation/package.json
packages/trace/package.json
packages/trim-whitespace/package.json
packages/wait-until-defined/package.json
yarn.lock

- Updates the deploy script
----

fix(root): updates deploy scripts

---

README.md
package.json
packages/debounce/README.md
packages/debounce/package.json
packages/debounce/src/index.test.ts
packages/debounce/src/index.ts
packages/debounce/tsconfig.json
packages/fllter-array/package.json
packages/head/package.json
packages/is-object/package.json
packages/kebab-to-camel-string/package.json
packages/merge-objects/package.json
packages/pipe/package.json
packages/repeat/package.json
packages/string-interpolation/package.json
packages/trace/package.json
packages/trim-whitespace/package.json
packages/wait-until-defined/package.json
yarn.lock

- Adds initial Debounce work
----

Init debounce

---

package.json
packages/throttle/README.md
packages/throttle/package.json
packages/throttle/src/index.test.ts
packages/throttle/src/index.ts
packages/throttle/tsconfig.json
packages/wait-until-defined/src/index.ts

feat(throttle): init throttle

---

packages/throttle/package.json

- Fixes some issues with the new throttle package's `package.json`
----

fix(throttle): fixes package.json

---

README.md
package.json
packages/rot13/README.md
packages/rot13/package.json
packages/rot13/src/index.test.ts
packages/rot13/src/index.ts
yarn.lock

- Adds initial Rot13 function
----

Fix helper

---

.gitignore
package.json
yarn.lock

- Fixes `minimist` security issue
----

feat(root): fixes minimist issue

---

.github/workflows/nodejs.yml

- Fixes gh-action `pnpm-lock.yaml` issue
----

fix(root): fixes gh action

---

.codependencerc
package.json
packages/new-pkg/package.json
packages/snake-to-camel-case/README.md
packages/snake-to-camel-case/package.json
packages/snake-to-camel-case/src/index.test.ts
packages/snake-to-camel-case/src/index.ts
packages/snake-to-camel-case/tsconfig.json
pnpm-lock.yaml

- Adds snake-to-camel-case pkg 📦
----

Init snake to camel case

---

package.json
packages/curry/README.md
packages/curry/package.json
packages/curry/src/index.test.ts
packages/curry/src/index.ts
packages/curry/tsconfig.json
pnpm-lock.yaml

Init curry

---

package.json

fix: adds script

---

.changeset/config.json

feat(root): adds changesets

---

packages/new-pkg/package.json

fix(root): makes new-pkg private

---

packages/curry/package.json

- Fixes packages for publish
----

fix(root): makes package public

---

.devcontainer/devcontainer.json
.devcontainer/dockerfile
.gitignore
pnpm-lock.yaml

Init dev container

---

.gitignore
README.md
package.json
packages/curry/src/index.ts
packages/new-pkg/package.json
packages/new-pkg/pkg/src/index.test.ts
packages/new-pkg/src/index.ts
packages/new-pkg/src/program.ts
packages/new-pkg/src/script.ts
packages/new-pkg/tsconfig.json
packages/update-markdown-list/README.md
packages/update-markdown-list/package.json
packages/update-markdown-list/src/cli.ts
packages/update-markdown-list/src/index.test.ts
packages/update-markdown-list/src/index.ts
packages/update-markdown-list/tsconfig.json

- Adds initial update-markdown-list
----

Add copy paste examples

---

.github/workflows/update.yml

chore: updates commit msg
